'use strict';
// UI fixtures only. No advertising APIs or production data are used.
const actions = [
 {id:1,word:'outdoor led lights',location:'SP 探索 / 户外照明组',object:'搜索词 · 广泛来源',action:'该停',color:'red',change:'建议精准否定',sub:'仅限当前广告组，保留其他搜索词',reason:'30 点击 · 0 单 · 花费 $15.00。达到 30 次点击与 3P（$15.00）止损线。',rule:'ZERO-STOP · 零单止损',rank:'自然位未知，不参与排名例外。',exit:'核对相关性及来源投放后由负责人确认。',state:'待负责人核对',executable:false},
 {id:2,word:'led strip lights bedroom',location:'SP 精准 / 卧室灯带组',object:'精准关键词 · 示例对象 K-002',action:'该降',color:'amber',change:'$0.80 → $0.68',sub:'关键词基础竞价降低 15%',reason:'40 点击 · 6 单 · 花费 $42.00 · 销售额 $120。ACOS 35% = 1.4T，命中降投区间。',rule:'ACOS-DOWN-15 · 有单控成本',rank:'自然位 #18 → #18，未命中排名改善例外。',exit:'执行后 7 天复核；归因未成熟则继续等待。禁止同一对象重复调整。',state:'可执行',executable:true,old:0.8,next:0.68},
 {id:3,word:'warm white led strip',location:'SP 精准 / 暖光组',object:'精准关键词 · 示例对象 K-003',action:'该降',color:'amber',change:'$0.70 → $0.63',sub:'关键词基础竞价降低 10%',reason:'50 点击 · 6 单 · 花费 $36.00 · 销售额 $120。ACOS 30% = 1.2T，命中降投区间。',rule:'ACOS-DOWN-10 · 有单控成本',rank:'自然位 #8，无完整排名历史；不启用趋势例外。',exit:'执行后 7 天复核新增点击、订单和 ACOS；样本不足交负责人判断。',state:'可执行',executable:true,old:0.7,next:0.63},
 {id:4,word:'under cabinet led lights',location:'SP 精准 / 厨房灯组',object:'精准关键词 · 示例对象 K-004',action:'该守',color:'gray',change:'保持 $0.55',sub:'无需后台操作',reason:'80 点击 · 10 单 · 花费 $50.00 · 销售额 $200。ACOS 25% = T，处于守投区间。',rule:'ACOS-HOLD · 达标维持',rank:'最近 7 天有 6 次排名记录，均为前 3；未授权减投试验。',exit:'下一分析周期复核，当前不登记为已执行。',state:'无需操作',executable:false},
 {id:5,word:'led rope lights',location:'SP 精准 / 装饰灯组',object:'精准关键词 · 示例对象 K-005',action:'该加',color:'green',change:'$0.60 → $0.66',sub:'关键词基础竞价提高 10%',reason:'60 点击 · 10 单 · 花费 $36.00 · 销售额 $200。ACOS 18% < 0.8T（20%）。',rule:'ACOS-UP · 达标扩量',rank:'自然位 #38；演示条件：当前设置齐全，无观察锁定，已核对无需加预算。',exit:'执行后 7 天复核；ACOS 超过 1.1T 时重新评估。加价不保证流量增长。',state:'可执行',executable:true,old:0.6,next:0.66},
 {id:6,word:'bedroom mood lighting',location:'SP 核心词 / 氛围灯组',object:'核心精准词 · 已授权排名观察',action:'该观察',color:'blue',change:'保持 $0.75',sub:'不追加放量',reason:'14 天 6 单 · ACOS 35% ≤ 1.5T；排名中位数 #20 → #15，改善 25% 且前进 5 位。',rule:'RANK-GROWTH · 核心词限额观察',rank:'前后两个 7 天窗口各有 6 次有效日排名记录。',exit:'最多额外 7 天或新增花费 $15（3P），先到先复核。ACOS >37.5% 时退出例外。',state:'观察中',executable:false},
 {id:7,word:'battery powered led lights',location:'SP 探索 / 电池灯组',object:'搜索词 · 样本不足',action:'该观察',color:'blue',change:'继续收集数据',sub:'不生成调价指令',reason:'8 点击 · 0 单 · 花费 $4.80。未达到降投所需 15 点击及 $7.50 花费。',rule:'SAMPLE-WAIT · 样本不足',rank:'排名未知，不补零。',exit:'7 天后或达到 15 点击且花费 $7.50 时复核；到期仍不足进入待我判。',state:'样本观察',executable:false}
];
const pending = [
 {word:'kitchen cabinet lighting',tag:'缺当前设置',text:'搜索词投产达到加投候选，但缺少当前竞价、预算和唯一投放对象，不能生成具体调整值。',need:'负责人需补充：当前投放设置报告，并核对是否已有精准投放。'},
 {word:'room decor lights',tag:'执行对象冲突',text:'同一广泛投放下，部分搜索词达到止损线，其他搜索词表现良好；不能直接暂停整条广泛投放。',need:'负责人需确认：搜索词相关性及精准否定范围；保留表现良好的其他流量。'}
];
const $ = selector => document.querySelector(selector);
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let filter='全部', records=[];
const labels=['该停','该降','该守','该加','该观察'];
function showView(name){document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===name);el.setAttribute('aria-selected',String(el.dataset.view===name));});}
function render(){
 const q=$('#search').value.trim().toLowerCase();
 const visible=actions.filter(r=>(filter==='全部'||r.action===filter)&&`${r.word} ${r.location}`.toLowerCase().includes(q));
 $('#cards').innerHTML=[...labels,'待我判'].map((label,i)=>`<button class="stat ${filter===label?'active':''}" data-filter="${label}" aria-pressed="${filter===label}"><span>${label}</span><i>${['↘','↓','—','↗','◷','?'][i]}</i><b>${label==='待我判'?pending.length:actions.filter(r=>r.action===label).length}</b><small>${['核对后停止无效消耗','收紧竞价，控制成本','维持当前投放','核对后逐步放量','有期限，有退出条件','缺数据或规则冲突'][i]}</small></button>`).join('');
 $('#filters').innerHTML=['全部',...labels].map(label=>`<button class="filter ${filter===label?'active':''}" data-filter="${label}" aria-pressed="${filter===label}">${label}${label==='全部'?' '+actions.length:''}</button>`).join('');
 $('#count').textContent=`${visible.length} 个对象`;
 $('#rows').innerHTML=visible.length?visible.map(r=>`<tr><td><strong>${esc(r.word)}</strong><small>${esc(r.location)}</small><small>${esc(r.object)}</small></td><td><span class="badge ${r.color}">${r.action}</span></td><td><strong>${esc(r.change)}</strong><small>${esc(r.sub)}</small></td><td>${esc(r.reason)}<small>${esc(r.rule)}</small></td><td><span class="badge ${records.some(x=>x.id===r.id)?'blue':r.executable?'green':'gray'}">${records.some(x=>x.id===r.id)?'人工登记 · 观察中':esc(r.state)}</span><br><button class="row-button" data-detail="${r.id}">查看操作 ↗</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">没有匹配的操作，试试其他关键词或筛选。</td></tr>';
 $('#pendingItems').innerHTML=pending.map(p=>`<div class="item"><span class="badge amber">${esc(p.tag)}</span><h3>${esc(p.word)}</h3><p>${esc(p.text)}</p><p><b>${esc(p.need)}</b></p><button class="row-button" data-upload>补充材料</button></div>`).join('');
 $('#reviewItems').innerHTML=records.length?records.map(r=>`<div class="item"><span class="badge blue">人工登记 · 未经后台核验</span><h3>${esc(r.word)}</h3><p>实际登记：$${r.old.toFixed(2)} → $${r.actual.toFixed(2)} · ${esc(r.time.toLocaleString('zh-CN'))}</p><p>复核时间：${esc(new Date(r.time.getTime()+7*86400000).toLocaleString('zh-CN'))}；最终判定需等待归因成熟。</p><p>演示中没有后续表现数据，不生成成功或失败结论。</p></div>`).join(''):'<div class="empty"><h3>还没有执行记录</h3><p>在可执行项目中试用「登记演示执行」，这里会显示独立的观察计时。</p><small>守投与保持观察不计为已执行操作。</small></div>';
}
function detail(id){const r=actions.find(x=>x.id===id);const recorded=records.some(x=>x.id===id);$('#detailContent').innerHTML=`<div class="dialog-head"><div><small>${esc(r.rule)}</small><h2>${esc(r.word)}</h2></div><button data-close="detail" aria-label="关闭">×</button></div><span class="badge ${r.color}">${r.action}</span><div class="detail-box"><small>后台定位</small><b>${esc(r.location)}</b><p>${esc(r.object)}</p><p>广告管理 → 对应活动 → 对应广告组 → ${r.id===1?'搜索词 / 否定投放':'投放'}。操作前核对对象与当前设置。</p></div><h3>建议操作：${esc(r.change)}</h3><p class="muted">${esc(r.sub)}</p><h3>为什么这样判断</h3><p class="muted">${esc(r.reason)}</p><p class="muted">${esc(r.rank)}</p><h3>观察与退出条件</h3><p class="muted">${esc(r.exit)}</p>${r.executable&&!recorded?`<label class="input-line">实际执行后的竞价（USD）<input id="actual" type="number" min="0.01" step="0.01" value="${r.next.toFixed(2)}" required></label><label class="ack"><input type="checkbox" id="ack">我已核对对象及当前竞价；这里只模拟人工登记，不操作广告后台。</label><div class="dialog-footer"><button class="secondary" data-close="detail">暂不登记</button><button class="primary" id="record" disabled>登记演示执行</button></div>`:`<div class="notice" style="margin-top:20px">${recorded?'该对象已有演示执行记录，观察期内不重复调整。':r.action==='该停'?'该项需负责人核对，实习生不能直接登记执行。':'当前无需执行后台改动，按退出条件复核。'}</div><div class="dialog-footer"><button class="primary" data-close="detail">了解</button></div>`}`;
 $('#detail').showModal();
 if($('#ack')){$('#ack').onchange=()=>$('#record').disabled=!$('#ack').checked;$('#record').onclick=()=>{const actual=Number($('#actual').value);if(!$('#actual').reportValidity())return;const delta=(actual-r.old)/r.old;if(Math.abs(delta)>0.200001||(r.action==='该降'&&actual>=r.old)||(r.action==='该加'&&actual<=r.old)){toast('实际值与建议方向不符，或超过单次 20% 上限，请交负责人确认。');return;}records.push({...r,actual,time:new Date()});$('#detail').close();render();toast('已登记演示执行，可在「执行与复盘」查看。');};}
}
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.filter){if(el.dataset.filter==='待我判'){showView('pending');return;}filter=el.dataset.filter;showView('actions');render();}if(el.dataset.view)showView(el.dataset.view);if(el.dataset.detail)detail(Number(el.dataset.detail));if(el.dataset.close)$('#'+el.dataset.close).close();if(el.hasAttribute('data-upload'))$('#upload').showModal();});
$('#search').addEventListener('input',render);
$('#uploadOpen').onclick=()=>$('#upload').showModal();$('#ruleOpen').onclick=()=>$('#rules').showModal();
$('#files').onchange=()=>{$('#fileList').innerHTML=Array.from($('#files').files).map(f=>`<div>✓ ${esc(f.name)} <small>${(f.size/1024).toFixed(1)} KB · 仅本地选中，未解析</small></div>`).join('')||'尚未选择文件';};
$('#export').onclick=()=>{const q=$('#search').value.trim().toLowerCase();const rows=actions.filter(r=>(filter==='全部'||r.action===filter)&&`${r.word} ${r.location}`.toLowerCase().includes(q));const csv=[['数据性质','关键词','位置','建议','调整','理由','退出条件'],...rows.map(r=>['演示数据，不可用于真实广告',r.word,r.location,r.action,r.change,r.reason,r.exit])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='广告操作清单-演示数据.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出当前筛选下的演示操作清单。');};
render();showView('actions');
